apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: applications
  namespace: argocd
spec:
  project: system
  source:
    repoURL: https://github.com/nnstt1/argocd-kustomize-helm-verify.git
    path: manifests/applications
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      selfHeal: true