apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-secrets-operator
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/nnstt1/argocd-kustomize-helm-verify.git
    path: manifests/vault-secrets-operator
  destination:
    namespace: vault-secrets-operator
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: false
    syncOptions:
          - CreateNamespace=true
